name: Create PR
on:
  workflow_dispatch:
jobs:
  new-pr:
    runs-on: ubuntu-latest
    name: create new pr
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: new pr
        run: |
          echo "Started"
          gh pr create --base master --head test-pr --title "NEW PR" --body "Everything works again"
          echo "Completed"
  
