name: "the 10 input limit"
on:
  workflow_dispatch:
    inputs:
      PARAMETERS:
        description: "A JSON object with all needed parameters"
        required: true
jobs:
  myJob:
    name: "My job"
    runs-on: ubuntu-latest
    steps:
      - name: step 2
        run: echo '${{ inputs.PARAMETERS }}' | jq -r '.MY_INPUT_1'
        
     

