name: "the 10 input limit"
on:
  workflow_dispatch:
    inputs:
      PARAMETERS:
        description: "A JSON object with all needed parameters"
        required: true
jobs:
  myJob:
    name: "My job"
    runs-on: ubuntu-latest
    steps:
      - name: step 2
        run: |
          declare -a arr=("MY_INPUT_1" "MY_INPUT_2" "MY_INPUT_3")
          for i in "${arr[@]}"
          do
             output=$(echo '${{ inputs.PARAMETERS }}' | jq -r '.'$i'')
             echo $output is result
          done
          
     

