name: "the 10 input limit"
on:
  workflow_dispatch:
    inputs:
      PARAMETERS:
        description: "A JSON object with all needed parameters"
        required: true
jobs:
  myJob:
    name: "My job"
    runs-on: ubuntu-latest
#     outputs:
#       MY_INPUT_1: ${{ steps.setup-inputs.outputs.MY_INPUT_1 }}
#       MY_INPUT_2: ${{ steps.setup-inputs.outputs.MY_INPUT_2 }}
    steps:
      - name: Setup inputs from json
        id: setup-inputs
        run: |
            echo '${{ inputs.PARAMETERS }}' | jq -r 'to_entries[]

      - name: step 2
        run: echo '${{ inputs.PARAMETERS }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"'
        
      - name: step 3
        run: echo '${{ inputs.PARAMETERS }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' | xargs -I '{}' echo "{}" 

