name: Parent workflow

on:
  workflow_dispatch:
    inputs:
      Release_Version:
        required: true
        type: string

jobs:
  set_run_name:
    runs-on: ubuntu-latest
    name: set run name
    steps:
      - name: curl
        run: |
          Health_Check_response = "HTTP/2 200"
          if [[ ( "$Health_Check_response" === "HTTP/2 200" ) ]];then
              echo "Application health is OK"
          else
              echo "Retrying.."
          fi
          
  
  # set_run_name:
  #   runs-on: ubuntu-latest
  #   name: set run name
  #   steps:
  #     - name: curl
  #       run: |
  #         MAX_RETRIES=3
  #         RETRIES=0
          
  #         while [ $RETRIES -lt $MAX_RETRIES ];do
          
  #           Health_Check_response=$(curl -o - -I -s https://www.google.com/ | grep "HTTP/2")
  #           if [ $? -eq 0 ];then
  #               echo Health_Check_response = $Health_Check_response
  #               if [[ ( "$Health_Check_response" == "HTTP/2 200" ) ]];then
  #                   echo "Application health is OK"
  #                   break
  #               else
  #                   echo "Retrying.."
  #                   sleep 10
  #               fi
  #           else
  #             echo "Error while checking application health. Retrying.."
  #           fi
  #           RETRIES=$((RETRIES=1))
  #         done

  #         if [$RETRIES -eq $MAX_RETRIES ];then
  #           echo "Max retries reached. Unable to fetch health check status."
  #         fi
              
        

