name: Parent workflow

on:
  workflow_dispatch:

jobs:
  set_variable:
    name: set_variable
    runs-on: ubuntu-latest
    outputs: 
      rel_ver: ${{ steps.set_variable.outputs.rel_ver }}
    steps:
      - name: set_variable
        id: set_variable
        run: |
          rel_version="22.02"
          echo "rel_ver=$rel_version" >> $GITHUB_OUTPUT
          echo $rel_ver
  call-child:
    needs: set_variable
    uses: ./.github/workflows/Reuseable-B.yml
    with:
      Release_Version: "${{needs.set_variable.outputs.rel_ver}}" 
