name: child workflow
on:
  workflow_dispatch:
    inputs:
      Release_Version:
        required: true
        type: string
  workflow_call:
    inputs:
      Release_Version: 
        required: true
        type: string
        
jobs:
  the_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          workflowAuthor="${{ github.actor }}"
          echo "$workflowAuthor is author"
          #echo "Release_Versin: ${{ inputs.Release_Version }}"
          echo "Release_Versin: ${{ inputs.Release_Version }}"
