name: Parent workflow

on:
  workflow_dispatch:
    inputs:
      Release_Version:
        required: true
        type: string

jobs:
  set_run_name:
    runs-on: ubuntu-latest
    name: set run name
    steps:
      - name: curl
        run: curl -o -I https://www.google.com/
        

